// Code generated by "go-enum -type=Mode"; DO NOT EDIT.

// Install go-enum by `go get install github.com/searKing/golang/tools/go-enum`
package prm

import (
	"database/sql"
	"database/sql/driver"
	"encoding"
	"encoding/json"
	"fmt"
	"strconv"
)

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Combo-0]
	_ = x[Triangle-1]
	_ = x[Rectangle-2]
	_ = x[Ellipse-3]
	_ = x[Circle-4]
	_ = x[RotateDirect-5]
	_ = x[Beziers-6]
	_ = x[RotatedEllipse-7]
	_ = x[Polygon-8]
}

const _Mode_name = "ComboTriangleRectangleEllipseCircleRotateDirectBeziersRotatedEllipsePolygon"

var _Mode_index = [...]uint8{0, 5, 13, 22, 29, 35, 47, 54, 68, 75}

func _() {
	var _nil_Mode_value = func() (val Mode) { return }()

	// An "cannot convert Mode literal (type Mode) to type fmt.Stringer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ fmt.Stringer = _nil_Mode_value
}

func (i Mode) String() string {
	if i >= Mode(len(_Mode_index)-1) {
		return "Mode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Mode_name[_Mode_index[i]:_Mode_index[i+1]]
}

// New returns a pointer to a new addr filled with the Mode value passed in.
func (i Mode) New() *Mode {
	clone := i
	return &clone
}

var _Mode_values = []Mode{0, 1, 2, 3, 4, 5, 6, 7, 8}

var _Mode_name_to_values = map[string]Mode{
	_Mode_name[0:5]:   0,
	_Mode_name[5:13]:  1,
	_Mode_name[13:22]: 2,
	_Mode_name[22:29]: 3,
	_Mode_name[29:35]: 4,
	_Mode_name[35:47]: 5,
	_Mode_name[47:54]: 6,
	_Mode_name[54:68]: 7,
	_Mode_name[68:75]: 8,
}

// ParseModeString retrieves an enum value from the enum constants string name.
// Throws an error if the param is not part of the enum.
func ParseModeString(s string) (Mode, error) {
	if val, ok := _Mode_name_to_values[s]; ok {
		return val, nil
	}
	return 0, fmt.Errorf("%s does not belong to Mode values", s)
}

// ModeValues returns all values of the enum
func ModeValues() []Mode {
	return _Mode_values
}

// IsAMode returns "true" if the value is listed in the enum definition. "false" otherwise
func (i Mode) Registered() bool {
	for _, v := range _Mode_values {
		if i == v {
			return true
		}
	}
	return false
}

func _() {
	var _nil_Mode_value = func() (val Mode) { return }()

	// An "cannot convert Mode literal (type Mode) to type encoding.BinaryMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryMarshaler = &_nil_Mode_value

	// An "cannot convert Mode literal (type Mode) to type encoding.BinaryUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.BinaryUnmarshaler = &_nil_Mode_value
}

// MarshalBinary implements the encoding.BinaryMarshaler interface for Mode
func (i Mode) MarshalBinary() (data []byte, err error) {
	return []byte(i.String()), nil
}

// UnmarshalBinary implements the encoding.BinaryUnmarshaler interface for Mode
func (i *Mode) UnmarshalBinary(data []byte) error {
	var err error
	*i, err = ParseModeString(string(data))
	return err
}

func _() {
	var _nil_Mode_value = func() (val Mode) { return }()

	// An "cannot convert Mode literal (type Mode) to type json.Marshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Marshaler = _nil_Mode_value

	// An "cannot convert Mode literal (type Mode) to type encoding.Unmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ json.Unmarshaler = &_nil_Mode_value
}

// MarshalJSON implements the json.Marshaler interface for Mode
func (i Mode) MarshalJSON() ([]byte, error) {
	return json.Marshal(i.String())
}

// UnmarshalJSON implements the json.Unmarshaler interface for Mode
func (i *Mode) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return fmt.Errorf("Mode should be a string, got %s", data)
	}

	var err error
	*i, err = ParseModeString(s)
	return err
}

func _() {
	var _nil_Mode_value = func() (val Mode) { return }()

	// An "cannot convert Mode literal (type Mode) to type encoding.TextMarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextMarshaler = _nil_Mode_value

	// An "cannot convert Mode literal (type Mode) to type encoding.TextUnmarshaler" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ encoding.TextUnmarshaler = &_nil_Mode_value
}

// MarshalText implements the encoding.TextMarshaler interface for Mode
func (i Mode) MarshalText() ([]byte, error) {
	return []byte(i.String()), nil
}

// UnmarshalText implements the encoding.TextUnmarshaler interface for Mode
func (i *Mode) UnmarshalText(text []byte) error {
	var err error
	*i, err = ParseModeString(string(text))
	return err
}

//func _() {
//	var _nil_Mode_value = func() (val Mode) { return }()
//
//	// An "cannot convert Mode literal (type Mode) to type yaml.Marshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Marshaler = _nil_Mode_value
//
//	// An "cannot convert Mode literal (type Mode) to type yaml.Unmarshaler" compiler error signifies that the base type have changed.
//	// Re-run the go-enum command to generate them again.
//	var _ yaml.Unmarshaler = &_nil_Mode_value
//}

// MarshalYAML implements a YAML Marshaler for Mode
func (i Mode) MarshalYAML() (interface{}, error) {
	return i.String(), nil
}

// UnmarshalYAML implements a YAML Unmarshaler for Mode
func (i *Mode) UnmarshalYAML(unmarshal func(interface{}) error) error {
	var s string
	if err := unmarshal(&s); err != nil {
		return err
	}

	var err error
	*i, err = ParseModeString(s)
	return err
}

func _() {
	var _nil_Mode_value = func() (val Mode) { return }()

	// An "cannot convert Mode literal (type Mode) to type driver.Valuer" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ driver.Valuer = _nil_Mode_value

	// An "cannot convert Mode literal (type Mode) to type sql.Scanner" compiler error signifies that the base type have changed.
	// Re-run the go-enum command to generate them again.
	var _ sql.Scanner = &_nil_Mode_value
}

func (i Mode) Value() (driver.Value, error) {
	return i.String(), nil
}

func (i *Mode) Scan(value interface{}) error {
	if value == nil {
		return nil
	}

	str, ok := value.(string)
	if !ok {
		bytes, ok := value.([]byte)
		if !ok {
			return fmt.Errorf("value is not a byte slice")
		}

		str = string(bytes[:])
	}

	val, err := ParseModeString(str)
	if err != nil {
		return err
	}

	*i = val
	return nil
}

// ModeSliceContains reports whether sunEnums is within enums.
func ModeSliceContains(enums []Mode, sunEnums ...Mode) bool {
	var seenEnums = map[Mode]bool{}
	for _, e := range sunEnums {
		seenEnums[e] = false
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			seenEnums[v] = true
		}
	}

	for _, seen := range seenEnums {
		if !seen {
			return false
		}
	}

	return true
}

// ModeSliceContainsAny reports whether any sunEnum is within enums.
func ModeSliceContainsAny(enums []Mode, sunEnums ...Mode) bool {
	var seenEnums = map[Mode]struct{}{}
	for _, e := range sunEnums {
		seenEnums[e] = struct{}{}
	}

	for _, v := range enums {
		if _, has := seenEnums[v]; has {
			return true
		}
	}

	return false
}
